### PR TITLE
Peer Review BRG-11 (US127)

### PR DESCRIPTION
**Pull request by swongcopado**
Hi Andy, can you please peer review this implementation?

### CODE REVIEW

**Comment by andy-stevenckwong** [comment]
Initial pass - logic is sound
could benefit from some additional documentation.

**Comment by swongcopado** [comment]
Thanks! Let me work on that.

**Comment by swongcopado** [comment]
Documentation added.

**Comment by andy-stevenckwong** [comment]
Looks better now.
Just realised that logic on calculation contains a bug. 
It doesn't handle a negative scenario.

**Comment by swongcopado** [comment]
Thanks for spotting that!
Fixed.

**Comment by andy-stevenckwong** [comment]
All good now. Will approve and you're good to go.

**Review by andy-stevenckwong — APPROVED** [review]
Approved!

**Pull request closed without merging**
